-- Options are automatically loaded before lazy.nvim startup
-- Default options that are alays set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additionl options here
--
--"
--
